########################################################################
# Copyright (c) 1988-2014 $organization$
#
# This software is provided by the author and contributors ``as is'' 
# and any express or implied warranties, including, but not limited to, 
# the implied warranties of merchantability and fitness for a particular 
# purpose are disclaimed. In no event shall the author or contributors 
# be liable for any direct, indirect, incidental, special, exemplary, 
# or consequential damages (including, but not limited to, procurement 
# of substitute goods or services; loss of use, data, or profits; or 
# business interruption) however caused and on any theory of liability, 
# whether in contract, strict liability, or tort (including negligence 
# or otherwise) arising in any way out of the use of this software, 
# even if advised of the possibility of such damage.
#
#   File: Makefile
#
# Author: $author$
#   Date: 12/8/2014
#
# Common Gcc Makefile for medusa medusad Executable
########################################################################

#
# C++ .cpp sources
#
medusad_EXE_CPP_SOURCES += \
${MEDUSA_SRC}/medusa/mt/mt.cpp \
${MEDUSA_SRC}/medusa/network/server/daemon/tcp/processor.cpp \
${MEDUSA_SRC}/medusa/network/server/daemon/tcp/connections.cpp \
${MEDUSA_SRC}/medusa/network/network.cpp \
${MEDUSA_SRC}/medusa/inet/http/server/daemon/main_instance.cpp \
${MEDUSA_SRC}/medusa/inet/http/server/daemon/main.cpp \
${MEDUSA_SRC}/medusa/console/main_main.cpp \


