########################################################################
# Copyright (c) 1988-2014 $organization$
#
# This software is provided by the author and contributors ``as is'' 
# and any express or implied warranties, including, but not limited to, 
# the implied warranties of merchantability and fitness for a particular 
# purpose are disclaimed. In no event shall the author or contributors 
# be liable for any direct, indirect, incidental, special, exemplary, 
# or consequential damages (including, but not limited to, procurement 
# of substitute goods or services; loss of use, data, or profits; or 
# business interruption) however caused and on any theory of liability, 
# whether in contract, strict liability, or tort (including negligence 
# or otherwise) arising in any way out of the use of this software, 
# even if advised of the possibility of such damage.
#
#   File: Makefile
#
# Author: $author$
#   Date: 12/8/2014
#
# Common Gcc Makefile for Xos medusad Executable
########################################################################

#
# user defines
#
medusad_USRDEFINES += \
$(medusa_USRDEFINES) \

#
# user includes
#
medusad_USRINCLUDES += \
$(medusa_USRINCLUDES) \

#
# user libdirs
#
medusad_USRLIBDIRS += \
$(medusa_USRLIBDIRS) \

#
# user c++ flags
#
medusad_USRCXXFLAGS += \
$(medusa_USRCXXFLAGS) \

#
# user c flags
#
medusad_USRCFLAGS += \
$(medusa_USRCFLAGS) \

#
# user ld flags
#
medusad_USRLDFLAGS += \
$(medusa_USRLDFLAGS) \

#
# C sources
#
medusad_C_SOURCES += \
$(medusa_C_SOURCES) \

#
# C++ .cc sources
#
medusad_CC_SOURCES += \
$(medusa_CC_SOURCES) \

#
# C++ .cxx sources
#
medusad_CXX_SOURCES += \
$(medusa_CXX_SOURCES) \

#
# C++ .cpp sources
#
medusad_CPP_SOURCES += \
$(medusa_CPP_SOURCES) \
${MEDUSA_SRC}/medusa/app/console/medusad/main.cpp \
${MEDUSA_SRC}/medusa/console/main_main.cpp \

#
# Objective C .m sources
#
medusad_M_SOURCES += \
$(medusa_M_SOURCES) \

#
# Objective C++ .mm sources
#
medusad_MM_SOURCES += \
$(medusa_MM_SOURCES) \

#
# libs
#
#LIBS += \
#-lsomelib
#
medusad_LIBS += \
$(medusa_LIBS) \

        

