########################################################################
# Copyright (c) 1988-2014 $organization$
#
# This software is provided by the author and contributors ``as is'' 
# and any express or implied warranties, including, but not limited to, 
# the implied warranties of merchantability and fitness for a particular 
# purpose are disclaimed. In no event shall the author or contributors 
# be liable for any direct, indirect, incidental, special, exemplary, 
# or consequential damages (including, but not limited to, procurement 
# of substitute goods or services; loss of use, data, or profits; or 
# business interruption) however caused and on any theory of liability, 
# whether in contract, strict liability, or tort (including negligence 
# or otherwise) arising in any way out of the use of this software, 
# even if advised of the possibility of such damage.
#
#   File: Makefile
#
# Author: $author$
#   Date: 12/8/2014
#
# Gcc Makefile for Xos libmedusa
########################################################################

#
# user defines
#
libmedusa_USRDEFINES += \
${medusa_USRDEFINES} \

#
# user includes
#
libmedusa_USRINCLUDES += \
${medusa_USRINCLUDES} \

#
# user libdirs
#
libmedusa_USRLIBDIRS += \
${medusa_USRLIBDIRS} \

#
# user c++ flags
#
libmedusa_USRCXXFLAGS += \
${medusa_USRCXXFLAG} \

#
# user c flags
#
libmedusa_USRCFLAGS += \
${medusa_USRCFLAGS} \

#
# user ld flags
#
libmedusa_USRLDFLAGS += \
${medusa_USRLDFLAGS} \

#
# C sources
#
libmedusa_LIB_C_SOURCES += \

#
# C++ .cc sources
#
libmedusa_LIB_CC_SOURCES += \

#
# C++ .cxx sources
#
libmedusa_LIB_CXX_SOURCES += \

#
# C++ .cpp sources
#
libmedusa_LIB_CPP_SOURCES += \
${MEDUSA_SRC}/medusa/inet/xttp/protocol/identifier.cpp \
${MEDUSA_SRC}/medusa/inet/xttp/protocol/name.cpp \
${MEDUSA_SRC}/medusa/inet/xttp/protocol/version.cpp \
${MEDUSA_SRC}/medusa/base/base.cpp \

#
# Objective C .m sources
#
libmedusa_LIB_M_SOURCES += \

#
# Objective C++ .mm sources
#
libmedusa_LIB_MM_SOURCES += \

#
# libs
#
libmedusa_LIBS = \
-lmedusa \
${medusa_LIBS} \

