########################################################################
# Copyright (c) 1988-2018 $organization$
#
# This software is provided by the author and contributors ``as is''
# and any express or implied warranties, including, but not limited to,
# the implied warranties of merchantability and fitness for a particular
# purpose are disclaimed. In no event shall the author or contributors
# be liable for any direct, indirect, incidental, special, exemplary,
# or consequential damages (including, but not limited to, procurement
# of substitute goods or services; loss of use, data, or profits; or
# business interruption) however caused and on any theory of liability,
# whether in contract, strict liability, or tort (including negligence
# or otherwise) arising in any way out of the use of this software,
# even if advised of the possibility of such damage.
#
#   File: Makefile
#
# Author: $author$
#   Date: 10/16/2018
#
# generic Gcc Makefile for medusa Library libmedusa
########################################################################


#
# target
#
libmedusa_LIBTARGET = libmedusa.${LIBEXT}

########################################################################

#
# user c++ flags
#
libmedusa_USRCXXFLAGS += \
${medusa_USRCXXFLAGS} \

#
# user defines
#
libmedusa_USRDEFINES += \
${medusa_USRDEFINES} \

#
# user includes
#
libmedusa_USRINCLUDES += \
${medusa_USRINCLUDES} \

#
# user libdirs
#
libmedusa_USRLIBDIRS += \
${medusa_USRLIBDIRS} \

########################################################################

#
# Library .c sources
#
#libmedusa_LIB_C_SOURCES += \
#${MEDUSA_SRC}/medusa/base/Base.c \

#
# Library .cc sources
#
#libmedusa_LIB_CC_SOURCES += \
#${MEDUSA_SRC}/medusa/base/Base.cc \

#
# Library .cxx sources
#
#libmedusa_LIB_CXX_SOURCES += \
#${MEDUSA_SRC}/medusa/base/Base.cxx \

#
# Library .cpp sources
#
libmedusa_LIB_CPP_SOURCES += \
${MEDUSA_SRC}/medusa/inet/xttp/protocol/identifier.cpp \
${MEDUSA_SRC}/medusa/inet/xttp/protocol/name.cpp \
${MEDUSA_SRC}/medusa/inet/xttp/protocol/version.cpp \

#
# Library .m sources
#
#libmedusa_LIB_M_SOURCES += \
#${MEDUSA_SRC}/medusa/base/Base.m \

#
# Library .mm sources
#
#libmedusa_LIB_MM_SOURCES += \
#${MEDUSA_SRC}/medusa/base/Base.mm \


########################################################################




